name: Publish Pre-Release to NPM
on:
  pull_request:
    types:
      - closed

jobs:
  publish_prerelease:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn bump prerelease
      - run: bin/publish --tag next
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
